### ISSUE TITLE
JSON file isn't parsed in library 

### ISSUE THREAD

**Issue by danielbouman** [GeneralSarsby/mjspylab#6]
When json file has a non-number data point, the file isn't parsed in de library

**Comment by GeneralSarsby** [comment]
> If allow_nan is true (the default), then NaN, Infinity, and -Infinity will be encoded as such. This behavior is not JSON specification compliant, but is consistent with most JavaScript based encoders and decoders. Otherwise, it will be a ValueError to encode such floats.

https://docs.python.org/2/library/json.html

i can change allow_nan in the json output to be False. this will cause a value error. hopefully causing the user to fix their scripts.

would this work?

**Comment by GeneralSarsby** [comment]
I propose trying to catch any bad values that arrive from the results, so that they are
encoded into the json correctly:

```import math
def _save_nan_inf(n):
    if math.isnan(n) or (n == np.inf) or (n == -np.inf):
        return None
    return n
#none maps to null to be valid json.
```

but also turning off the allow_nan option of the encoder: `json.dumps(d, allow_nan=False)`

**Comment by danielbouman** [comment]
Sounds good

**Comment by GeneralSarsby** [comment]
done.
